### ISSUE TITLE
Show tooltip on MouseOver on Web/Desktop

### ISSUE THREAD

**Issue by jlubeck** [imaNNeoFighT/fl_chart#275] opened 2020-03-31 15:43 UTC
This was discussed a bit here: https://github.com/imaNNeoFighT/fl_chart/issues/37#issuecomment-517467347 but it was never implemented although the poster claimed it was working.

**Comment by hahnrobert** [comment] 2020-08-11 05:05
Any updates on this? -- This seems to be an easy fix and super valuable.

**Comment by shripal-is-in** [comment] 2021-01-09 12:56
Any idea/ETA when this will be implemented?

**Comment by imaNNeoFighT** [comment] 2021-01-09 13:13
I am as busy as a bee. I will do my best to implement it ASAP.
Thanks for being patient.

**Comment by shripal-is-in** [comment] 2021-01-09 13:35
If you can guide me through the source code for this issue, maybe I can make a PR?

**Comment by shripal-is-in** [comment] 2021-01-11 15:16
@imaNNeoFighT correct me if I'm wrong,
This can be achieved by wrapping https://github.com/imaNNeoFighT/fl_chart/blob/master/lib/src/chart/line_chart/line_chart.dart#L46 the GestureDetector in a MouseRegion and handling the mouse entries and exits according to the onPan methods inside the GestureDetector?

**Comment by imaNNeoFighT** [comment] 2021-01-12 05:18
I think that works. It is pretty close to what I think.

**Comment by shripal-is-in** [comment] 2021-01-12 08:07
Okay, I'll try my best with this approach and create a PR when ready. Are there any test cases to be executed before i should make a PR?

**Comment by shripal17** [comment] 2021-01-16 11:42
Hi @imaNNeoFighT 
I have implemented the MouseRegion wrap for line chart, bar chart and pie chart, it was causing unexpected behavior for scatter chart, so didn't make changes to it. Can you do it for scatter chart or guide me for the same

Also done some improvements to example app for web, please check

**Comment by stuartkuentzel** [comment] 2021-03-16 05:07
I see that a PR was merged for this, are there any examples on how to use show tooltip on mouseover? Thanks!

**Comment by imaNNeoFighT** [comment] 2021-03-20 22:37
Now we support mouse hover in our latest version (0.20.1).

**Closed by imaNNeoFighT** 2021-03-20 22:37 UTC
Labels: Desktop, enhancement
