### ISSUE TITLE
Zoom in/out on line chart

### ISSUE THREAD

**Issue by dhs9004** [imaNNeoFighT/fl_chart#612] opened 2021-03-21 14:24 UTC
First at all, thank you so much for has such as amazing features on this repository.

It will be awesome if we can enable an zoom in/out option for the chart line, it you are projecting 10k data it is hard to see the true behavior of the data without zoom it.

Thanks,

**Comment by imaNNeoFighT** [comment] 2021-03-21 23:48
Hi, thank you.
Duplicate of #71.

**Closed by imaNNeoFighT** 2021-03-21 23:48 UTC
