### ISSUE TITLE
Pie chart swapping data causes render box exception if animation enabled

### ISSUE THREAD

**Issue by shababhsiddique** [imaNNeoFighT/fl_chart#829] opened 2021-11-28 12:15 UTC
I have a simple donut chart with data changed from provider on demand. When I do swap it gives a render exception.

The following assertion was thrown during a scheduler callback:
Updated layout information required for RenderLimitedBox#ebf03 NEEDS-LAYOUT NEEDS-PAINT to calculate
semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2747 pos 12: '!_needsLayout'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack:
#2      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2747:12)
#3      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2769:61)
#4      ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3430:14)
#5      RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2854:5)
#6      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2764:5)
#7      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2769:61)
#8      RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3146:14)
#9      RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2854:5)
#10     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2764:5)
#11     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2769:61)
#12     ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3430:14)
#13     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2854:5)
#14     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2764:5)
#15     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2769:61)
#16     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3146:14)
#17     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2854:5)
#18     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2764:5)
#19     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2769:61)
#20     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3146:14)
#21     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2854:5)
#22     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2764:5)
#23     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2769:61)
#24     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3146:14)
#25     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2854:5)
#26     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2764:5)
#27     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2769:61)
#28     ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3430:14)
#29     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2854:5)
#30     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2764:5)
#31     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2769:61)
#32     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3146:14)
#33     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2854:5)
#34     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2764:5)
#35     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2769:61)
#36     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3146:14)
#37     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2854:5)
#38     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2764:5)
#39     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2769:61)
#40     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3146:14)
#41     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2854:5)
#42     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2764:5)
#43     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2725:41)
#44     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1080:16)
#45     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:458:21)
#46     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#47     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#48     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#49     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#50     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#54     _invoke (dart:ui/hooks.dart:166:10)
#55     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#56     _drawFrame (dart:ui/hooks.dart:129:31)
(elided 5 frames from class _AssertionError and dart:async)

It renders fine visually, but this exception occur very randomly(sometime goes smoothly without exception with same data) when I switch data between income and expense

**To Reproduce**
Code of the pie chart 
` AspectRatio(
            aspectRatio: 1,
            child: PieChart(
              PieChartData(
                borderData: FlBorderData(
                  show: false,
                ),
                sectionsSpace: 0,
                centerSpaceRadius: 41,
                startDegreeOffset: -90,
                sections: _generateSections(),
              ),
            ),
          ),     

List<PieChartSectionData> _generateSections() {
    List<PieChartSectionData> piePieces = [];

    int index = 0;
    for (var pieceInfo in sortedCategoryPieces) {
      final isTouched = index == selectedPieIndex;
      final fontSize = isTouched ? 12.0 : 10.0;
      final radius = isTouched ? 38.0 : 34.0;
      final percentage =
          ((pieceInfo.total / grandTotal) * 100).toStringAsFixed(2);

      piePieces.add(PieChartSectionData(
        color: hexColor(pieceInfo.category.color),
        value: pieceInfo.total + 1,
        showTitle: isTouched,
        title: "$percentage%",
        radius: radius,
        titlePositionPercentageOffset: 1,
        titleStyle: TextStyle(
            fontSize: fontSize,
            fontWeight: FontWeight.w500,
            color: SpenderColors.text,
            backgroundColor: SpenderColors.scaffoldBackground),
      ));
      index++;
    }
    return piePieces;
  }
 `

data is from provider

**Versions**
 fl_chart: ^0.40.2
  flutter: 2.5.3

**Comment by shababhsiddique** [comment] 2021-11-28 13:03
The exception goes away when I set 
              swapAnimationDuration: Duration.zero,

so I guess it occur when there is not enough items in the pie to animate? this seem silly how do I get around this?

**Comment by NickJokic** [comment] 2021-11-30 11:39
+1, same

**Comment by imaNNeoFighT** [comment] 2021-12-03 21:28
I need a reproducible code to work on it.

**Comment by Eliathoran** [comment] 2021-12-22 12:59
This can be reproduced by having a ScaffoldMessenger shown in a stateless widget that has the chart.

@shababhsiddique solutions works, but sadly removes the animation :(

**Comment by imaNNeoFighT** [comment] 2022-01-28 13:40
It is a duplicate of #861
I made a fix right now on `dev` branch.
You need to wait for the next version. 

Please follow it in #861.

**Closed by imaNNeoFighT** 2022-01-28 13:40 UTC
Labels: Pie Chart, Needs Reproducible Code
