### ISSUE TITLE
upgrade to flutter 3.0

### ISSUE THREAD

**Issue by guchengxi1994** [imaNNeoFighT/fl_chart#998] opened 2022-05-12 08:10 UTC
WidgetsBinding.instance!.addPostFrameCallback 'WidgetsBinding' which excludes null

**Comment by techouse** [comment] 2022-05-12 10:16
Duplicate of https://github.com/imaNNeoFighT/fl_chart/issues/997

**Closed** 2022-05-12 11:45 UTC
