### ISSUE TITLE
I want to customize the icon on the left. Is there such a setting option? Or can you give me some hints, what should I do?

### ISSUE THREAD

**Issue by paintingStyle** [imaNNeoFighT/fl_chart#832] opened 2021-11-30 06:43 UTC
**我想自定义左边的图标。有这样的设置选项吗？或者你能给我一些提示吗，我该怎么办？**

**谢谢！**

LineChartData只能设置左标题，我需要设置左图标

<img width="99" alt="image" src="https://user-images.githubusercontent.com/22866404/143998835-3219dcbf-7351-4058-963b-6c742ceb110f.png">

```
LineChartData mainData() {
    return LineChartData(
      ....
      titlesData: FlTitlesData(
        show: true,
        leftTitles: SideTitles(
          showTitles: true,
          interval: 1,
          getTextStyles: (context, value) => const TextStyle(
            color: Color(0xff67727d),
            fontWeight: FontWeight.bold,
            fontSize: 15,
          ),
          getTitles: (value) {
            switch (value.toInt()) {
              case 1:
                return '1';
              case 2:
                return '2';
              case 3:
                return '3';
              case 4:
                return '4';
            }
            return '0';
          },
          reservedSize: 32,
          margin: 12,
        ),
      ),
      ....
      ],
    );
  }
```

**Comment by imaNNeoFighT** [comment] 2021-12-04 21:47
Duplicate of #567.
Please post your sajmple image there to follow up.

**Closed by imaNNeoFighT** 2021-12-04 21:47 UTC
