### ISSUE TITLE
"showingTooltipIndicators" causes Range Error.

### ISSUE THREAD

**Issue by namzug16** [imaNNeoFighT/fl_chart#852] opened 2021-12-11 12:53 UTC
## The bug
When changing the amount of data provided to a bar chart I get a Range Error:
```
======== Exception caught by rendering library =====================================================
The following IndexError was thrown during paint():
RangeError (index): Index out of range: index should be less than 3: 3

The relevant error-causing widget was: 
  BarChart BarChart:file:///home/gustavo/FlutterProjects/fl_charts_bug/lib/main.dart:89:14
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 581:7             _get]
packages/fl_chart/src/chart/bar_chart/bar_chart_painter.dart 588:21           [_drawTouchTooltip]
packages/fl_chart/src/chart/bar_chart/bar_chart_painter.dart 66:9             paint
packages/fl_chart/src/chart/bar_chart/bar_chart_renderer.dart 81:14           paint
packages/flutter/src/rendering/object.dart 2403:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                             paintChild
packages/flutter/src/rendering/proxy_box.dart 140:14                          paint
packages/flutter/src/rendering/object.dart 2403:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                             paintChild
packages/flutter/src/rendering/box.dart 2792:14                               defaultPaint
packages/flutter/src/rendering/flex.dart 1078:7                               paint
packages/flutter/src/rendering/object.dart 2403:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                             paintChild
packages/flutter/src/rendering/shifted_box.dart 79:14                         paint
packages/flutter/src/rendering/object.dart 2403:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                             paintChild
packages/flutter/src/rendering/box.dart 2792:14                               defaultPaint
packages/flutter/src/rendering/custom_layout.dart 408:5                       paint
packages/flutter/src/rendering/object.dart 2403:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                             paintChild
packages/flutter/src/rendering/proxy_box.dart 140:14                          paint
packages/flutter/src/material/material.dart 554:11                            paint
packages/flutter/src/rendering/object.dart 2403:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                             paintChild
packages/flutter/src/rendering/proxy_box.dart 140:14                          paint
packages/flutter/src/rendering/object.dart 392:12                             pushLayer
packages/flutter/src/rendering/proxy_box.dart 1929:14                         paint
packages/flutter/src/rendering/object.dart 2403:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                             paintChild
packages/flutter/src/rendering/proxy_box.dart 140:14                          paint
packages/flutter/src/rendering/object.dart 2403:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 189:12                             paintChild
packages/flutter/src/rendering/proxy_box.dart 140:14                          paint
packages/flutter/src/rendering/object.dart 2403:7                             [_paintWithContext]
packages/flutter/src/rendering/object.dart 141:10                             _repaintCompositedChild
packages/flutter/src/rendering/object.dart 100:5                              repaintCompositedChild
packages/flutter/src/rendering/object.dart 973:29                             flushPaint
packages/flutter/src/rendering/binding.dart 499:19                            drawFrame
packages/flutter/src/widgets/binding.dart 883:13                              drawFrame
packages/flutter/src/rendering/binding.dart 363:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1145:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1082:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 996:5                             [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1005:13                           invoke
lib/_engine/engine/platform_dispatcher.dart 159:5                             invokeOnDrawFrame
lib/_engine/engine.dart 455:45                                                <fn>
The following RenderObject was being processed when the exception was fired: RenderBarChart#d9fae
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=600.0, h=400.0)
...  size: Size(600.0, 400.0)
RenderObject: RenderBarChart#d9fae
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=600.0, h=400.0)
  size: Size(600.0, 400.0)
====================================================================================================
``` 
First of all I thought the error might have been caused by the data's count difference, for example from 3 items to 5, but this did not seem to be the caused, then when I was stylizing a bit more the chart I realized that the source of the problem was the ```showingTooltipIndicator``` parameter.

When I comment it or simply don't use it, I don't get the error, However it would be great to have it on my chart.

## To Reproduce
```dart
class MyData {
  const MyData(this.x, this.y);

  final double x;
  final double y;
}

const List<MyData> three = [
  MyData(0, 46),
  MyData(1, 19),
  MyData(2, 5),
];

const List<MyData> five = [
  MyData(0, 4),
  MyData(1, 90),
  MyData(2, 30),
  MyData(3, 10),
  MyData(4, 15),
];

class FlChartBug extends StatefulWidget {
  const FlChartBug({Key? key}) : super(key: key);

  @override
  State<FlChartBug> createState() => _FlChartBugState();
}

class _FlChartBugState extends State<FlChartBug> {
  List<MyData> data = three;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextButton(
                onPressed: () => setState(() {
                      data = three;
                    }),
                child: const Text("3 items")),
            TextButton(
                onPressed: () => setState(() {
                      data = five;
                    }),
                child: const Text("5 items")),
            Chart(data: data),
          ],
        ),
      ),
    );
  }
}

class Chart extends StatelessWidget {
  const Chart({Key? key, required this.data}) : super(key: key);

  final List<MyData> data;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 400,
      width: 600,
      child: BarChart(
        BarChartData(
          maxY: 100,
          titlesData: FlTitlesData(
            show: false,
          ),
          gridData: FlGridData(
            show: false,
          ),
          borderData: FlBorderData(
            show: false,
          ),
          barTouchData: BarTouchData(
            enabled: false,
          ),
          barGroups: [
            for (final item in data)
              BarChartGroupData(
                x: item.x.toInt(),
                barRods: [
                  BarChartRodData(
                    y: item.y,
                    width: 10,
                  ),
                ],
                showingTooltipIndicators: [0],
              ),
          ],
        ),
      ),
    );
  }
}
```

**Versions**
 - Flutter -> 2.8.0
 - FlChart -> 0.40.6

**Comment by SuricateTrading** [comment] 2021-12-12 12:37
This is a duplicate of [#840](https://github.com/imaNNeoFighT/fl_chart/issues/840).
Im glad that Im not the only one who gets the exception :)

**Comment by imaNNeoFighT** [comment] 2022-02-14 19:07
I will close it, let's follow it in #840.

**Closed by imaNNeoFighT** 2022-02-14 19:07 UTC
