### ISSUE TITLE
Don't scalable

### ISSUE THREAD

**Issue by Okladnoj** [imaNNeoFighT/fl_chart#609] opened 2021-03-19 12:23 UTC
**Don't make a duplicate issue.**
Response from **scalable** did'n result

**Is your feature request relasted to a problem? Please describe.**
I want scale graphic

**Describe the solution you'd like**
Change zoom with gesture

**Describe alternatives you've considered**
Used library flutter_echarts, but than not support **desctop** and **Null safety**

https://user-images.githubusercontent.com/36802187/111787025-24ab2f00-88c7-11eb-9c29-7411a7d2f8c2.mp4

**Additional context**
Thank you for such a great job.

**Comment by imaNNeoFighT** [comment] 2021-03-19 22:24
Duplicate of #71

**Closed by imaNNeoFighT** 2021-03-19 22:24 UTC
