### ISSUE TITLE
Strange line behaviour

### ISSUE THREAD

**Issue by Ferdzzzzzzzz** [imaNNeoFighT/fl_chart#144] opened 2019-12-25 08:44 UTC
Hi there, I'm getting this strange behaviour with all the graphs that I try to use, am I missing some setting? I can't find anything on it. This is straight from the line chart sample code :) 
<img width="593" alt="Screenshot 2019-12-25 at 10 23 03" src="https://user-images.githubusercontent.com/36441314/71439672-2fe2cf80-2703-11ea-8808-7004af709e5a.png">

**Comment by imaNNeoFighT** [comment] 2019-12-25 09:19
WTF,
 :))))
May I ask you your `fl_chart` version?

**Comment by Ferdzzzzzzzz** [comment] 2019-12-25 09:24
@imaNNeoFighT thanks for the quick response, I'm using 0.6.0, installed it today so should be latest? 👍

**Comment by imaNNeoFighT** [comment] 2019-12-25 09:29
You're welcome,
yes, it is the latest.
I will check it out ASAP.
Thanks for report.

**Comment by imaNNeoFighT** [comment] 2019-12-25 10:07
I couldn't reproduce it.
It's working correctly on my machine :)

**Comment by Ferdzzzzzzzz** [comment] 2019-12-25 10:55
Hmmm, thanks for checking, I'll start from scratch and see what happens :)

**Comment by imaNNeoFighT** [comment] 2019-12-25 13:13
Ok, waiting for you

**Comment by Ferdzzzzzzzz** [comment] 2019-12-25 13:51
@imaNNeoFighT I should have probably mentioned I'm building a web app 🤦‍♂ it's working for mobile, do you know why it's doing that on Flutter web? Is it something I can try to fix for you? :)

**Comment by Ferdzzzzzzzz** [comment] 2019-12-25 14:24
I see there is already a ticket open for flutter web, you can close this one if it's bothering you, thanks for the help 😄

**Comment by imaNNeoFighT** [comment] 2019-12-25 20:51
Oh man, I didn't know that you are testing it on the web :)
We have an already opened issue,
BTW, I think there is a workaround [here](https://github.com/imaNNeoFighT/fl_chart/issues/95#issuecomment-564279758) but I didn't test it.
It will be great if you help me to fix it with a temporary hack.
Feel free to ask me anything and make the Pull Request.
Thanks!

**Comment by imaNNeoFighT** [comment] 2019-12-25 20:52
I will close it, and we can follow it up in #95.

**Closed by imaNNeoFighT** 2019-12-25 20:52 UTC
Labels: bug
