### ISSUE TITLE
Question: Is it possible to have multiple y-axes?

### ISSUE THREAD

**Issue by alexanderwwagner** [imaNNeoFighT/fl_chart#1199] opened 2023-01-06 13:23 UTC
**Question**
At the moment I switch from Html5/JS/CSS to flutter and try to get a nice working chart for my roomdata.
In the past I used the apex chart library and was able to have multiple y-axes like in the picture I added below.
Is it possible to have multiple y-axes with the fl_chart library? I did not found something like that in the examples or the documentation.

Thank you!

![grafik](https://user-images.githubusercontent.com/45471644/211020188-fb35d940-8a6a-42e3-b174-50a56ac24f40.png)

**Comment by imaNNeoFighT** [comment] 2023-01-15 17:09
Duplicate of #429

**Closed by imaNNeoFighT** 2023-01-15 17:09 UTC
