### ISSUE TITLE
Hover support for Flutter Web

### ISSUE THREAD

**Issue by EdgarEscobedoHdz** [imaNNeoFighT/fl_chart#376] opened 2020-06-10 22:06 UTC
First of all, I want to thank you guys fur the hard work and the love put in this library, is AMAZING! (and way easier to use than the Google library). I'm wondering if there is any plan to support hover for Flutter Web enthusiasts like me. I saw that there was a request on this before but it got closed with no description.

Thanks in advance! Keep the good work going!

**Comment by imaNNeoFighT** [comment] 2020-06-11 04:14
Hi, you're welcome, man!
Yes, definitely we will implement it on both web and desktop.
Stay tuned.
Thanks!

**Comment by jlubeck** [comment] 2020-06-15 16:07
This looks like a duplicate of https://github.com/imaNNeoFighT/fl_chart/issues/275

**Comment by imaNNeoFighT** [comment] 2020-06-15 16:15
Good catch!

**Closed by imaNNeoFighT** 2020-06-15 16:15 UTC
Labels: Web, enhancement

**Comment by denkoul** [comment] 2020-11-30 10:44
any updates?
