### ISSUE TITLE
The bug when drawing pie chart inside the scrollable widgets

### ISSUE THREAD

**Issue by romatroskin** [imaNNeoFighT/fl_chart#178] opened 2020-01-21 13:42 UTC
Hello! I get an issue drawing pie chart inside the Stack view widget which is inside the SliverList and inside a CustomScrollView, you can see the result on screenshot below. But seems like the issue not in the Stack, probably because of scrollable views, the chart are not fit for some reason and clipped out:

<img width="303" alt="Screenshot at Jan 21 15-42-04" src="https://user-images.githubusercontent.com/6350260/72809604-a15f6080-3c64-11ea-8cfa-b94847e0338c.png">

**Comment by imaNNeoFighT** [comment] 2020-02-06 18:17
I think it is redundant,
#179, If you accept, please close it.
Thanks!

**Comment by imaNNeoFighT** [comment] 2020-02-06 18:18
Because there is a reproducible code in #179.

**Comment by romatroskin** [comment] 2020-02-07 14:26
Looks like, and I've noticed when I put chart to the column, top and bottom are not clipped and when I put chat to the row left and right not clipped, but can not be done for both sides.

**Comment by imaNNeoFighT** [comment] 2020-03-06 20:52
Fixed in 0.8.1, thanks for reporting.

**Closed by imaNNeoFighT** 2020-03-06 20:52 UTC
Labels: Pie Chart, bug
