### ISSUE TITLE
Doesnt' work with big data

### ISSUE THREAD

**Issue by andynguy3n** [imaNNeoFighT/fl_chart#54] opened 2019-08-03 05:15 UTC
Currently,
I'm fetching the data from this API (https://api.coincap.io/v2/assets/bitcoin/history?interval=d1)

I created a FlSpot with these values:
`FlSpot(2757.4283650019844275, 1501718400000.1)`

The chart doesn't work and the app stops working as well.

**Comment by tauitdnmd** [comment] 2019-08-03 10:21
I'm having the same issue too. 
It doesn't work with a big value.

**Comment by sukhcha-in** [comment] 2019-08-06 18:59
@andynguy3n @tauitdnmd I was having similar issue, when large data is passed app becomes unresponsive and might crash too.
Instead of passing values directly to chart calculate the percentage of each value between 0-100 then use it in fl_chart.

**Comment by Dhuliang** [comment] 2019-08-15 02:33
Same issue

**Comment by imaNNeoFighT** [comment] 2019-08-20 08:03
Sore for delay, I've tried with the values that you said:
<img src="https://user-images.githubusercontent.com/7009300/63328846-1e00b280-c346-11e9-9ae6-aa17bb668430.png" width="400" />

And it works just fine!
<img src="https://user-images.githubusercontent.com/7009300/63328886-2fe25580-c346-11e9-9537-66511beafc5e.png" width="400" />

May I ask you use the **latest version** of fl_chart, and check it again?

**Comment by imaNNeoFighT** [comment] 2019-08-23 19:36
It's gonna be closed if I don't get any answer in a day because I tested it and it works in new versions.

**Comment by andynguy3n** [comment] 2019-08-24 07:02
Thanks @imaNNeoFighT ,
I'll test it again soon.

**Comment by imaNNeoFighT** [comment] 2019-08-29 23:15
Unfortunately, I'm gonna close it soon

**Closed** 2019-09-05 17:19 UTC
Labels: bug

**Comment by andynguy3n** [comment] 2019-09-20 15:10
I think with a big list, it doesn't work.
`flutter: 728`
The list with 728 items.

```
  @override
  Widget build(BuildContext context) {
    print(listSpots().length);
    return FlChart(
      chart: LineChart(
        LineChartData(
          lineBarsData: [LineChartBarData(spots: listSpots(), isCurved: true)],
        ),
      ),
    );
  }
```

```
  List<FlSpot> listSpots() => this
      .data
      .map((assetData) =>
          FlSpot(assetData.time.toDouble(), double.parse(assetData.priceUsd)))
      .toList();
```

![Screen Shot 2019-09-20 at 10 10 36 PM](https://user-images.githubusercontent.com/10527554/65338009-7ea83700-dbf3-11e9-9f96-6b4322bc4fe6.png)

**Comment by imaNNeoFighT** [comment] 2019-09-27 08:14
Hi guys, I know your problem, but not sure what could we do,
I think you guys can scale down your values to fix this problem, is it works?

**Comment by andynguy3n** [comment] 2019-09-28 10:07
Thanks. I'll try. Have a good day.

**Comment by 18601673727** [comment] 2022-03-06 21:07
For `minY: 70833.02` and `maxY: 116880.3`, I have this chart with 12 dots, `x` ranges from `1` to `12`, render with `LineChart` got result like this:
<img width="427" alt="截屏2022-03-07 上午5 04 36" src="https://user-images.githubusercontent.com/3302620/156942237-9eda8757-1e61-4429-9080-af69fbb3dce7.png">
@imaNNeoFighT  Please help...

**Comment by imaNNeoFighT** [comment] 2022-03-06 21:42
Hi @18601673727 
What's the problem?

**Comment by 18601673727** [comment] 2022-03-06 22:35
> Hi @18601673727 What's the problem?

The line just looks too art-y don't you think sir?

**Comment by imaNNeoFighT** [comment] 2022-03-06 22:38
Sorry I didn't understand.

**Comment by 18601673727** [comment] 2022-03-06 23:33
> Sorry I didn't understand.

I mean I'm expecting the line to be still "singe-directioned" not twisted when `y` value of the dots get greater than certain value or by any other circumstances.

**Comment by imaNNeoFighT** [comment] 2022-03-07 21:05
Can you give me your simplified code to reproduce?

**Comment by RodolfoSilva** [comment] 2022-04-24 01:15
I think you can use this class to help you scale the values to keep the number inside the range configured to `fl_chart`.

```dart
class ScaledValue {
  ScaledValue({
    required this.sourceRangeMin,
    required this.sourceRangeMax,
    required this.targetRangeMin,
    required this.targetRangeMax,
  });

  final num sourceRangeMin;
  final num sourceRangeMax;
  final num targetRangeMin;
  final num targetRangeMax;

  double calc(num value) {
    final targetRange = targetRangeMax - targetRangeMin;
    final sourceRange = sourceRangeMax - sourceRangeMin;

    return (value - sourceRangeMin) * targetRange / sourceRange +
        targetRangeMin;
  }
}

void main() {
  final scale = ScaledValue(
    sourceRangeMin: 4500,
    sourceRangeMax: 10000,
    targetRangeMin: 1,
    targetRangeMax: 10,
  );

  print(scale.calc(10000)); // 10
  print(scale.calc(8000));  // 6.72727272....
  print(scale.calc(4500));  // 1
}
```
