### ISSUE TITLE
Sizing for Pie Chart related to closed issue #179 not working

### ISSUE THREAD

**Issue by KJonesDevelopment** [imaNNeoFighT/fl_chart#353] opened 2020-05-24 21:29 UTC
After following issue #179 I expected a container around the pie chart to re-size the chart.  However, a small container cuts it and I cannot size it larger with a larger container.  Is there any way to set the outer radius of the pie chart?  
<img width="365" alt="Screen Shot 2020-05-24 at 4 23 15 PM" src="https://user-images.githubusercontent.com/48265018/82765288-12fa1780-9ddb-11ea-99ee-f3cb8394daa1.png">
<img width="368" alt="Screen Shot 2020-05-24 at 4 24 23 PM" src="https://user-images.githubusercontent.com/48265018/82765289-14c3db00-9ddb-11ea-98a7-6e46396961df.png">

Code for screenshots: 

`child: Container(
          height: 100.0,
          width: 100.0,
          child: PieChart(
            PieChartData(
                centerSpaceRadius: 50.0,
                centerSpaceColor: Colors.transparent,
                sectionsSpace: 0.0,
                startDegreeOffset: 0.0,
                sections: [
                  PieChartSectionData(
                    value: 35.0,
                    color: Colors.transparent,
                    showTitle: false,
                  ),
                  PieChartSectionData(
                    value: 5.0,
                    color: Colors.lightGreen,
                    showTitle: false,
                  ),
                  PieChartSectionData(
                    value: 10.0,
                    color: Colors.blueGrey,
                    showTitle: false,
                  ),
                  PieChartSectionData(
                    value: 20.0,
                    color: Colors.cyan,
                    showTitle: false,
                  ),
                ]
            ),
          ),
        ),`

`child: Container(
          height: 370.0,
          width: 370.0,
          child: PieChart(
            PieChartData(
                centerSpaceRadius: 50.0,
                centerSpaceColor: Colors.transparent,
                sectionsSpace: 0.0,
                startDegreeOffset: 0.0,
                sections: [
                  PieChartSectionData(
                    value: 35.0,
                    color: Colors.transparent,
                    showTitle: false,
                  ),
                  PieChartSectionData(
                    value: 5.0,
                    color: Colors.lightGreen,
                    showTitle: false,
                  ),
                  PieChartSectionData(
                    value: 10.0,
                    color: Colors.blueGrey,
                    showTitle: false,
                  ),
                  PieChartSectionData(
                    value: 20.0,
                    color: Colors.cyan,
                    showTitle: false,
                  ),
                ]
            ),
          ),
        ),`

**Comment by abdullahayyad** [comment] 2020-07-01 12:23
try to change `centerSpaceRadius` value that's why it is not fit with SizeBox or Container, if you want to change pie size dynamic by parent widget just add `centerSpaceRadius: double.infinity`,  it works with me

**Comment by imaNNeoFighT** [comment] 2020-08-10 18:39
Hi, sorry for the late answer,
I think it has been fixed in [0.10.1](https://github.com/imaNNeoFighT/fl_chart/releases/tag/0.10.1), check the changelog.
and let me know if it is still exists.

**Comment by imaNNeoFighT** [comment] 2020-08-29 21:45
Did you check it?
Please let me know whether it is fixed or not.
Thanks!

**Comment by mrdc** [comment] 2021-04-19 10:50
> Did you check it?
> Please let me know whether it is fixed or not.
> Thanks!

@imaNNeoFighT 

Hi, unfortunately, it's not fixed for me: `Container()` with predefined width and height is not forcing the chart to fit inside of it.
```
Fl_chart: 0.30.0
Flutter: 2.0.5
```

**Comment by imaNNeoFighT** [comment] 2021-04-19 16:57
Give me reproducible code.

**Comment by mrdc** [comment] 2021-04-20 10:44
> Give me reproducible code.
@imaNNeoFighT 
Here you go:

![Untitled](https://user-images.githubusercontent.com/16876990/115383179-2fb2f100-a1de-11eb-9e85-b1a331a0af4b.png)

Looks like it's related to `final double radius = isTouched ? 60 : 50;` `Radius` overrides constraints from `Container()`. 

```dart
int touchedIndex;
      
  child: Container(
    color: Colors.green,
    width: 150,
    height: 100,
    child: PieChart(
      PieChartData(
          pieTouchData: PieTouchData(
        touchCallback: (pieTouchResponse) {
                setState(() {
                  final desiredTouch =
                      pieTouchResponse.touchInput
                              is! PointerExitEvent &&
                          pieTouchResponse.touchInput
                              is! PointerUpEvent;
                  if (desiredTouch &&
                      pieTouchResponse
                              .touchedSection !=
                          null) {
                    touchedIndex = pieTouchResponse
                        .touchedSection
                        .touchedSectionIndex;
                  } else {
                    touchedIndex = -1;
                  }
                });
              },
              ),
          borderData: FlBorderData(
            show: false,
          ),
          sectionsSpace: 5,
          centerSpaceRadius: 25,
          sections: sectionsData(
              touchedIndex)),
    ),
  ),


List<PieChartSectionData> sectionsData (int touchedIndex) {
  return List.generate(2, (i) {
    final isTouched = i == touchedIndex;
    final double fontSize = isTouched ? 25 : 16;
    final double radius = isTouched ? 60 : 50;
    switch (i) {
      case 0:
        return PieChartSectionData(
          color: const Color(0xff845bef),
          value: 20.0,
          title: '20',
          radius: radius,
          titleStyle: TextStyle(
              fontSize: fontSize,
              fontWeight: FontWeight.bold,
              color: const Color(0xffffffff)),
        );
      case 1:
        return PieChartSectionData(
          color: const Color(0xff13d38e),
          value: 30.0,
          title: '30',
          radius: radius,
          titleStyle: TextStyle(
              fontSize: fontSize,
              fontWeight: FontWeight.bold,
              color: const Color(0xffffffff)),
        );
      default:
        return null;
    }
  });
}
```

**Comment by imaNNeoFighT** [comment] 2021-04-30 14:21
Please put it in a main.dart file, then I can run it directly.

**Comment by yasaman93** [comment] 2021-06-23 15:08
Unfortunately, I have the same issue

**Comment by imaNNeoFighT** [comment] 2021-07-02 08:59
@yasaman93 please provide a reproducible code (a main.dart file)

**Comment by imaNNeoFighT** [comment] 2021-11-03 21:57
@hamdi-99 There is no reproducible code yet to check.

**Comment by lisamartin00** [comment] 2021-11-30 19:26
Hi @imaNNeoFighT does this get you want you need?

`main.dart`
```
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'fl_chart Pie Chart Sizing Bug',
      home: Scaffold(
          appBar: AppBar(
            title: Text('fl_chart Pie Chart Sizing Bug'),
          ),
          body: Container(
            width: 300.0,
            height: 300.0,
            color: Colors.blue,
            child: PieChart(
              PieChartData(
                sections: [
                  PieChartSectionData(
                    value: 60.0,
                    color: Colors.green,
                  ),
                  PieChartSectionData(
                    value: 40.0,
                    color: Colors.purple,
                  ),
                ],
                centerSpaceRadius: 0,
              ),
            ),
          )),
    );
  }
}
```

<img width="399" alt="Screen Shot 2021-11-30 at 12 23 33 PM" src="https://user-images.githubusercontent.com/6465955/144114199-2db6c65a-11cf-40b4-9705-fdd8683d5a1f.png">

I hope this is reflective of the same issue everyone else is experiencing. I would expect my pie chart to fill the size of its parent container, but it does not.

**Comment by imaNNeoFighT** [comment] 2021-12-03 21:28
Each [PieChartSectionData](https://github.com/imaNNeoFighT/fl_chart/blob/master/repo_files/documentations/pie_chart.md#piechartsectiondata) has a `radius` value (which the default is 40).
It determines how much radius each section should have.

In your example. You didn't provide anything. It draws based on the default value.

You need to set `150` (half of `300`) to fill the area (keep in mind that it is a hard-coded value).
Otherwise, wrap your PieChart with a [LayoutBuilder](https://api.flutter.dev/flutter/widgets/LayoutBuilder-class.html) to get the current size of the parent and set the `radius` dynamically.

Check the below sample (source code is [here](https://gist.github.com/imaNNeoFighT/336b1674e3036e626ec475fe2ad10afe)):

https://user-images.githubusercontent.com/7009300/144674885-fb777413-d631-4314-a284-11237cec86f1.mp4

**Closed by imaNNeoFighT** 2021-12-03 21:28 UTC
Labels: bug, Pie Chart, Needs Reproducible Code
