### ISSUE TITLE
Different y value than hover value

### ISSUE THREAD

**Issue by vgraphics** [imaNNeoFighT/fl_chart#1185] opened 2022-11-07 23:28 UTC
Hello to all,
I am trying to implement a double data chart and I am trying to normalize the values of the second chart to be the same scale as first one. The problem is that the normalized value is not the correct one and is only used for the scale. Can we add a different y value at FlSpot class than the value shown in the hover??

**Comment by imaNNeoFighT** [comment] 2023-01-15 13:57
Duplicate of #429

**Closed by imaNNeoFighT** 2023-01-15 13:57 UTC
Labels: duplicate
